#!/bin/sh
CLASSPATH=$CLASSPATH:/opt/info/courses/COMP28112/ex2/libraries/commons-httpclient-3.0.1.jar
CLASSPATH=$CLASSPATH:/opt/info/courses/COMP28112/ex2/libraries/commons-codec-1.3.jar
CLASSPATH=$CLASSPATH:/opt/info/courses/COMP28112/ex2/libraries/commons-logging-1.1.jar
CLASSPATH=$CLASSPATH:/opt/info/courses/COMP28112/ex2/libraries/xalan.jar
CLASSPATH=$CLASSPATH:/opt/info/courses/COMP28112/ex2/libraries/xercesImpl.jar
CLASSPATH=$CLASSPATH:/opt/info/courses/COMP28112/ex2/libraries/serializer.jar
javac -classpath $CLASSPATH $*
