#!/bin/sh
# NB: you run from the root of the uk/ac/manchester/... hierarchy
CLASSPATH=$CLASSPATH:/opt/info/courses/COMP28112/ex2/libraries/commons-httpclient-3.0.1.jar
CLASSPATH=$CLASSPATH:/opt/info/courses/COMP28112/ex2/libraries/commons-codec-1.3.jar
CLASSPATH=$CLASSPATH:/opt/info/courses/COMP28112/ex2/libraries/commons-logging-1.1.jar
CLASSPATH=$CLASSPATH:/opt/info/courses/COMP28112/ex2/libraries/xalan.jar
CLASSPATH=$CLASSPATH:/opt/info/courses/COMP28112/ex2/libraries/xercesImpl.jar
CLASSPATH=$CLASSPATH:/opt/info/courses/COMP28112/ex2/libraries/serializer.jar

java -classpath $CLASSPATH -Djavax.xml.parsers.DocumentBuilderFactory=org.apache.xerces.jaxp.DocumentBuilderFactoryImpl -Djavax.xml.transform.TransformerFactory=org.apache.xalan.xsltc.trax.TransformerFactoryImpl $*
